### ISSUE TITLE
dumb question: how to disable the vertical line for all files EXCEPT git commit messages?

### ISSUE THREAD

**Issue by warren-bank** [atom/wrap-guide#68]
The vertical line is super annoying when writing code.. and I currently have the package globally disabled. But I'd like to know how to configure it so that (when re-enabled) the guide line is ONLY displayed when writing `git commit` messages.

[this](https://github.com/atom/autoflow/issues/2) seems relevant.. and issue #17 seems to discuss how to migrate this config from the older deprecated pattern to using scopes.. but none of my attempts to edit `config.cson` give the desired outcome.

Incidentally, the [documentation](https://flight-manual.atom.io/using-atom/sections/basic-customization/#global-configuration-settings) still mentions the deprecated way to configure "wrap-guide".

Anyway, I was hoping that somebody who understands the internals could give a super simple (but complete) example of a `config.cson` that would configure "wrap-guide" to be disabled for all file types EXCEPT when editing a git commit message (72 chars). That would be __super__ helpful. Thanks.

**Comment by lexicalunit** [comment]
You can do this via stylesheets. Go to

- Atom > Stylesheet...

And add

```less
atom-text-editor:not([data-grammar="text git-commit"]) .wrap-guide {
  display: none !important;
}
```

This will have the effect of completely hiding the wrap-guide, except when you're editing a git-commit message. Note that this relies on the syntax being properly set to "Git Commit Message" in the editor.

**Comment by warren-bank** [comment]
@lexicalunit  ..thanks so much for your help. I'll give it a try.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by warren-bank** [comment]
as a final comment for anyone else interested in doing this (or similar)..
the following also appears to work nicely:

in file: `~/.atom/config.cson`

minimal necessary configuration:

```text
"*":
  "wrap-guide":
    enabled: false
    column: -1
".git-commit.text":
  "wrap-guide":
    enabled: true
    column: 72
```
